name: Tests

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 12 * * 1"

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      INWX_USERNAME: ${{ secrets.INWX_USERNAME }}
      INWX_PASSWORD: ${{ secrets.INWX_PASSWORD }}
      ZONE: "test-${{ github.run_id }}.com"
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19

    - name: Test
      run: go test -v ./...
